---
- hosts: all
  vars:
    home: "{{ ansible_env.HOME }}"
    utils:
      - htop
      - gnome-terminal
      - zsh
      - tmux
      - vim
      - git

    projects:
      - path: love-polygon
        git: git@github.com:gasnew/love-polygon.git

      - path: lancenger
        git: git@github.com:gasnew/lancenger.git


  roles:
    - role: viasite-ansible.zsh
      become: yes
      vars:
        zsh_antigen_bundles_extras:
          - joel-porquet/zsh-dircolors-solarized
        zsh_autosuggestions_bind_key: "^U"
    - common
