---
- hosts: all
  vars:
    home: "{{ ansible_env.HOME }}"
    utils:
      - git
      - gnome-terminal
      - htop
      - silversearcher-ag
      - tmux
      - vim
      - yarn
      - zsh

    projects:
      - path: love-polygon
        git: git@github.com:gasnew/love-polygon.git

      - path: lancenger
        git: git@github.com:gasnew/lancenger.git

  roles:
    - common
    - role: viasite-ansible.zsh
      become: yes
      vars:
        zsh_aliases:
          - { alias: 'gs', action: 'git status' }
          - { alias: 'gl', action: 'git log' }
        zsh_antigen_bundles_extras:
          - git
          - joel-porquet/zsh-dircolors-solarized
        zsh_autosuggestions_bind_key: "^T"
    - role: tvieira.powerline-fonts
      vars:
        all_users:
          - user: garrettsnewman
            homedir: "{{ home }}"
        all_fonts:
          - DroidSansMono
